spring:
  application:
<<<<<<< HEAD
    name: user-center
=======
    name: yupao
>>>>>>> master
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://58.87.96.8:3306/user-center
    username: user-center
    password: 12345678
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
<<<<<<< HEAD
  # Redis配置
  redis:
    port: 6379
    host: 58.87.96.8
    database: 0
    password: 12345678
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
=======
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis配置
  data:
    redis:
      host: 58.87.96.8
      port: 6379
      password: 12345678
      database: 0
>>>>>>> master
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: oceanbo.cn
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
knife4j:
  enable: true
  openapi:
    group:
      default:
        api-rule: package
        api-rule-resources:
<<<<<<< HEAD
          - com.example.usercenter.controller
=======
          - com.example.yupao.controller
>>>>>>> master
